name: Run Python Script in utils

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'week*/README.md'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    

      - name: Run Python script
        run: |
          cd utils
          python update_daily_tasks_all.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'sooyeon-kr'
          git config --global user.email 'sooyeon7027@naver.com'
          git add .
          git diff --cached --quiet || git commit -m ":calendar: weekly task summary"
          git push

